### ISSUE TITLE
RxJava2 with Socket.IO

### ISSUE THREAD

**Issue by zishanj** [yfain/rxjava2#1]
I came up to your slideshare presentation after googling for RxJava2 tutorials. It was really helpful in understanding the basic concept of using RxJava2. I am experimenting with RxJava2 and Socket.IO. 

In Socket.IO all I need is to establish a connection and then wait for any events like EVENT_CONNECT, EVENT_CONNECT_ERROR and EVENT_CONNECTING, so I could know when the internet is dropped and Socket.IO is trying to re-establish the connection. Then I need another event listener like MESSAGE to know when message is arriving.

What do you think is the best approach for above in RxJava2. Did you came up with any such sample?

**Comment by yfain** [comment]
I didn't have a chance to work with RxJava+ Socket.IO, but I had a similar task in RxJS (a JavaScript implementation of RX) talking to the server via a WebSocket. This example (written in TypeScript) may give you some ideas about writing a class that wraps socket messages into an Observable: https://github.com/Farata/angulartypescript/blob/master/MEAP_v3/chapter13/client/src/app/wsservice/app.component.ts
